<?php


use Klaviyo\Profiles as Klaviyo;
use PHPUnit\Framework\TestCase;
use GuzzleHttp\Client;

class ProfilesTest extends TestCase
{
    protected $test_KLAVIYO;
    protected $test_client;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->test_KLAVIYO = new Klaviyo(
            'ABCDEF',
            'pk_TESTPRIVATEKEY'
        );

        $this->test_client = new Client(
            ['base_uri' => Klaviyo::HOST]
        );

    }

    public function testGetProfile()
    {
        print_r( $this->test_KLAVIYO->getProfile( 'RCbFX2') );
    }

    public function testGetProfileMetricTimeline()
    {
        print_r( $this->test_KLAVIYO->getProfileMetricTimeline( 'RCbFX2', 'MidALd') );
    }

    public function testUpdateProfile()
    {
        print_r( $this->test_KLAVIYO->updateProfile( 'RCbFX2', ['\'$title="test"\''] ) );
    }

    public function testGetProfileAllMetricsTimeline()
    {
        print_r( $this->test_KLAVIYO->getProfileAllMetricsTimeline( 'RCbFX2') );
    }
}
