<?php


use Klaviyo\Profiles as Klaviyo;
use PHPUnit\Framework\TestCase;
use GuzzleHttp\Client;

class ProfilesTest extends TestCase
{
    protected $test_KLAVIYO;
    protected $test_client;

    public function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->test_KLAVIYO = new Klaviyo(
            'LzPPzc',
            'pk_857aa1e36cbca43fb873d7404ee716cba9');

        $this->test_client = new Client(
            ['base_uri' => Klaviyo::HOST]
        );

    }

    public function testGetProfile()
    {
        print_r( $this->test_KLAVIYO->getProfile( 'RCbFX2') );
    }

    public function testGetProfileMetricTimeline()
    {
        print_r( $this->test_KLAVIYO->getProfileMetricTimeline( 'RCbFX2', 'MidALd') );
    }

    public function testUpdateProfile()
    {
        print_r( $this->test_KLAVIYO->updateProfile( 'RCbFX2', ['\'$title="test"\''] ) );
        $this->test_client->put('https://a.klaviyo.com/api/v1/person/RCbFX2?api_key=pk_857aa1e36cbca43fb873d7404ee716cba9', ['$title' =>'test'] );
    }

    public function testGetProfileAllMetricsTimeline()
    {
        print_r( $this->test_KLAVIYO->getProfileAllMetricsTimeline( 'RCbFX2') );
    }
}
